In [1]:
#!pip install scikit-learn==1.0.1

In [1]:
import sklearn
sklearn.__version__

'1.1.1'

In [2]:
#importing the libraries
import numpy as np
import pandas as pd

In [3]:

import os, types
import pandas as pd
from botocore.client import Config
import ibm_boto3

def __iter__(self): return 0

# @hidden_cell
# The following code accesses a file in your IBM Cloud Object Storage. It includes your credentials.
# You might want to remove those credentials before you share the notebook.
client_11d6882aba4a4088b92e5b1911d45304 = ibm_boto3.client(service_name='s3',
    ibm_api_key_id='sx6PViCs9d4juEujZh94EWrhvABrI9WcyD79TtPhj172',
    ibm_auth_endpoint="https://iam.cloud.ibm.com/oidc/token",
    config=Config(signature_version='oauth'),
    endpoint_url='https://s3.private.us.cloud-object-storage.appdomain.cloud')

body = client_11d6882aba4a4088b92e5b1911d45304.get_object(Bucket='vitdemo-donotdelete-pr-rmotdmlpnl04gy',Key='50_Startups.csv')['Body']
# add missing __iter__ method, so pandas accepts body as file-like object
if not hasattr(body, "__iter__"): body.__iter__ = types.MethodType( __iter__, body )

data = pd.read_csv(body)
data.head()


ModuleNotFoundError: No module named 'ibm_boto3'

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 108 entries, 0 to 107
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   R&D Spend        108 non-null    float64
 1   Administration   108 non-null    float64
 2   Marketing Spend  108 non-null    float64
 3   State            108 non-null    object 
 4   Profit           108 non-null    float64
dtypes: float64(4), object(1)
memory usage: 4.3+ KB


In [6]:
data.describe()

R&D Spend  Administration  Marketing Spend         Profit
count     108.000000      108.000000       108.000000     108.000000
mean    74959.338704   121750.788889    214952.664722  113523.760000
std     44996.368152    27322.385654    117937.942120   38991.013654
min         0.000000    51283.140000         0.000000   14681.400000
25%     38558.510000   105077.645000    134050.070000   90708.190000
50%     75791.365000   122699.795000    239452.750000  109543.120000
75%    101913.080000   145077.580000    298664.470000  141585.520000
max    165349.200000   182645.560000    471784.100000  192261.830000

In [7]:
data.isnull().any()

R&D Spend          False
Administration     False
Marketing Spend    False
State              False
Profit             False
dtype: bool

In [8]:
data['State'].unique()

array(['New York', 'California', 'Florida'], dtype=object)

In [9]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
data['State']= le.fit_transform(data['State'])

In [10]:
data

R&D Spend  Administration  Marketing Spend  State     Profit
0    165349.20       136897.80        471784.10      2  192261.83
1    162597.70       151377.59        443898.53      0  191792.06
2    153441.51       101145.55        407934.54      1  191050.39
3    144372.41       118671.85        383199.62      2  182901.99
4    142107.34        91391.77        366168.42      1  166187.94
..         ...             ...              ...    ...        ...
103  119943.24       156547.42        256512.92      1  132602.65
104  114523.61       122616.84        261776.23      2  129917.04
105   78013.11       121597.55        264346.06      0  126992.93
106   94657.16       145077.58        282574.31      2  125370.37
107   91749.16       114175.79        294919.57      1  124266.90

[108 rows x 5 columns]

In [11]:
x= data.iloc[:,0:4].values
y= data.iloc[:,4:5].values

In [12]:
x.shape

(108, 4)

In [13]:
y.shape

(108, 1)

In [14]:
from sklearn.preprocessing import OneHotEncoder
one = OneHotEncoder()
z= one.fit_transform(x[:,3:4]).toarray()

In [15]:
z

array([[0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0

In [16]:
x= np.delete(x,3,axis = 1)
x= np.concatenate((z,x),axis=1)

In [17]:
x.shape

(108, 6)

In [18]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2, random_state=0)

In [19]:
x_train.shape

(86, 6)

In [20]:
x_test.shape

(22, 6)

In [21]:
#model building
from sklearn.linear_model import LinearRegression
mlr = LinearRegression()
mlr.fit(x_train,y_train)

LinearRegression()

In [22]:
ypred= mlr.predict(x_test)
ypred

array([[ 48466.75433417],
       [134429.39628446],
       [ 76093.94745793],
       [181201.94746511],
       [113069.45110036],
       [134397.50337433],
       [128842.89457941],
       [159664.83856912],
       [116952.09718498],
       [ 46372.47771261],
       [102406.37641003],
       [115207.87076438],
       [ 48466.75433417],
       [119345.51846305],
       [ 88717.92542862],
       [127301.68084921],
       [127301.68084921],
       [ 91145.83032983],
       [ 58337.13774601],
       [146474.04747225],
       [149038.44713346],
       [152718.63782935]])

In [23]:
y_test

array([[ 64926.08],
       [146121.95],
       [ 90708.19],
       [191050.39],
       [108552.04],
       [144259.4 ],
       [124266.9 ],
       [155752.6 ],
       [126992.93],
       [ 42559.73],
       [101004.64],
       [110352.25],
       [ 64926.08],
       [111313.02],
       [ 89949.14],
       [134307.35],
       [134307.35],
       [ 96712.8 ],
       [ 49490.75],
       [129917.04],
       [132602.65],
       [152211.77]])

In [24]:
from sklearn.metrics import r2_score
acc= r2_score(y_test,ypred)
acc

0.9262629717101227

In [25]:
#predict the value on random inputs
mlr.predict([[0,0,1,12345,23453,34567]])

array([[59488.98239515]])

In [26]:
import pickle
pickle.dump(mlr,open("model.pkl","wb"))

In [27]:
pwd

'/home/wsuser/work'

# Deployment

URLS Dallas: https://us-south.ml.cloud.ibm.com, London - https://eu-gb.ml.cloud.ibm.com, Frankfurt - https://eu-de.ml.cloud.ibm.com, Tokyo - https://jp-tok.ml.cloud.ibm.com

In [28]:
!pip install -U ibm-watson-machine-learning

     |████████████████████████████████| 1.7 MB 25.2 MB/s eta 0:00:01
  Attempting uninstall: ibm-watson-machine-learning
    Found existing installation: ibm-watson-machine-learning 1.0.208
    Uninstalling ibm-watson-machine-learning-1.0.208:
      Successfully uninstalled ibm-watson-machine-learning-1.0.208


In [29]:
from ibm_watson_machine_learning import APIClient
import json
import numpy as np

# Authenticate and Set Space

In [30]:
wml_credentials = {
    "apikey":"oiXUdbwKFqHbkZTR6ZHXgLl5DWH3_p0i9knkXNeVhgeP",
    "url":"https://us-south.ml.cloud.ibm.com"
}

In [31]:
wml_client = APIClient(wml_credentials)
wml_client.spaces.list()

Note: 'limit' is not provided. Only first 50 records will be displayed if the number of records exceed 50
------------------------------------  ----------------------  ------------------------
ID                                    NAME                    CREATED
60295b97-1414-4e2e-8f18-dbb9c405edeb  digi_naturalist_deploy  2022-05-19T11:20:14.210Z
fe115531-b04d-4351-9731-a7716ac0cb10  Demo_model              2022-04-26T14:24:15.077Z
d5df6caa-8646-4351-a233-8aaf0fc411f8  insurance_test          2021-12-10T12:45:34.373Z
ed4bbae4-67e9-434e-a012-1dfe88af795b  Insurance_deploy        2021-12-10T09:50:25.401Z
------------------------------------  ----------------------  ------------------------


In [32]:
SPACE_ID = "fe115531-b04d-4351-9731-a7716ac0cb10"

In [33]:
wml_client.set.default_space(SPACE_ID)

'SUCCESS'

In [34]:
wml_client.software_specifications.list(500)

-------------------------------  ------------------------------------  ----
NAME                             ASSET_ID                              TYPE
default_py3.6                    0062b8c9-8b7d-44a0-a9b9-46c416adcbd9  base
kernel-spark3.2-scala2.12        020d69ce-7ac1-5e68-ac1a-31189867356a  base
pytorch-onnx_1.3-py3.7-edt       069ea134-3346-5748-b513-49120e15d288  base
scikit-learn_0.20-py3.6          09c5a1d0-9c1e-4473-a344-eb7b665ff687  base
spark-mllib_3.0-scala_2.12       09f4cff0-90a7-5899-b9ed-1ef348aebdee  base
pytorch-onnx_rt22.1-py3.9        0b848dd4-e681-5599-be41-b5f6fccc6471  base
ai-function_0.1-py3.6            0cdb0f1e-5376-4f4d-92dd-da3b69aa9bda  base
shiny-r3.6                       0e6e79df-875e-4f24-8ae9-62dcc2148306  base
tensorflow_2.4-py3.7-horovod     1092590a-307d-563d-9b62-4eb7d64b3f22  base
pytorch_1.1-py3.6                10ac12d6-6b30-4ccd-8392-3e922c096a92  base
tensorflow_1.15-py3.6-ddl        111e41b3-de2d-5422-a4d6-bf776828c4b7  base
runtime-22.1

# Save and Deploy the model

In [36]:
import sklearn
sklearn.__version__

'1.0.2'

In [37]:
MODEL_NAME = 'DemoModel'
DEPLOYMENT_NAME = 'demo_deploy'
DEMO_MODEL = mlr

In [48]:
# Set Python Version
software_spec_uid = wml_client.software_specifications.get_id_by_name('runtime-22.1-py3.9')

In [49]:
# Setup model meta
model_props = {
    wml_client.repository.ModelMetaNames.NAME: MODEL_NAME, 
    wml_client.repository.ModelMetaNames.TYPE: 'scikit-learn_1.0', 
    wml_client.repository.ModelMetaNames.SOFTWARE_SPEC_UID: software_spec_uid 
}

In [50]:
#Save model
model_details = wml_client.repository.store_model(
    model=DEMO_MODEL, 
    meta_props=model_props, 
    training_data=x_train, 
    training_target=y_train
)

In [51]:
model_details

{'entity': {'hybrid_pipeline_software_specs': [],
  'label_column': 'l0',
  'software_spec': {'id': '12b83a17-24d8-5082-900f-0ab31fbfd3cb',
   'name': 'runtime-22.1-py3.9'},
  'training_data_references': [{'connection': {'access_key_id': 'not_applicable',
     'endpoint_url': 'not_applicable',
     'secret_access_key': 'not_applicable'},
    'id': '1',
    'location': {},
    'schema': {'fields': [{'name': 'f0', 'type': 'float'},
      {'name': 'f1', 'type': 'float'},
      {'name': 'f2', 'type': 'float'},
      {'name': 'f3', 'type': 'float'},
      {'name': 'f4', 'type': 'float'},
      {'name': 'f5', 'type': 'float'}],
     'id': '1',
     'type': 'ndarray'},
    'type': 's3'}],
  'type': 'scikit-learn_1.0'},
 'metadata': {'created_at': '2022-05-30T10:55:55.615Z',
  'id': 'c2c5b18a-7a6a-431b-8c89-75d9361f07e1',
  'modified_at': '2022-05-30T10:55:59.206Z',
  'name': 'DemoModel',
  'owner': 'IBMid-665001JLNH',
  'resource_key': 'e5f120f1-cc77-4e86-af13-c4456cbdaa58',
  'space_id': 'fe

In [52]:
model_id = wml_client.repository.get_model_id(model_details)

In [53]:
model_id

'c2c5b18a-7a6a-431b-8c89-75d9361f07e1'

In [54]:
# Set meta
deployment_props = {
    wml_client.deployments.ConfigurationMetaNames.NAME:DEPLOYMENT_NAME, 
    wml_client.deployments.ConfigurationMetaNames.ONLINE: {}
}


In [55]:
# Deploy
deployment = wml_client.deployments.create(
    artifact_uid=model_id, 
    meta_props=deployment_props 
)



#######################################################################################

Synchronous deployment creation for uid: 'c2c5b18a-7a6a-431b-8c89-75d9361f07e1' started

#######################################################################################


initializing
Note: online_url is deprecated and will be removed in a future release. Use serving_urls instead.

ready


------------------------------------------------------------------------------------------------
Successfully finished deployment creation, deployment_uid='08bac2cf-1f16-4f7a-a47f-eff02351dab0'
------------------------------------------------------------------------------------------------


